# Generated by Django 2.2.7 on 2019-11-26 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Key', max_length=1024)),
                ('content', models.CharField(default='', max_length=1024)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
